/**
 * Public machine-readable API contract for call center integration (no auth to read this spec).
 * Handover: Niranga — use GET /api/call-center/public/request-data
 */

export const CALL_CENTER_PUBLIC_META = {
  service: "BMS Pro Black — Call Center API",
  basePath: "/api/call-center",
  productionExampleBaseUrl: "https://black.bmspros.com.au/api/call-center",
  handoverContact: "Niranga",
  documentationFile: "CALL_CENTER_API.md (repo root, admin panel)",
  postmanCollection: "postman/BMS_Call_Center_API.postman_collection.json",
  authentication: {
    requiredForMostEndpoints: true,
    type: "HTTP Bearer",
    tokenSource:
      "Firebase Authentication — same project as BMS. Call center agents sign in with email/password; send ID token as Authorization: Bearer <idToken>",
    agentProfileCollection: "Firestore: call_center_agents/{firebaseUid}",
  },
  tenantScoping: {
    description:
      "Workshop tenant is ownerUid (workshop owner's Firebase UID). Send as query ?ownerUid=... or header X-Tenant-Id.",
  },
  notes: [
    "This JSON describes request/response shapes only. It does not grant access to data.",
    "Webhook registration exists at POST /webhooks (CC admin); dispatch to external URLs must be wired separately if not yet in codebase.",
  ],
} as const;

export type PublicEndpointSpec = {
  id: string;
  method: "GET" | "POST" | "PATCH" | "DELETE";
  path: string;
  authRequired: boolean;
  description: string;
  headers?: { name: string; required: boolean; when?: string; example?: string }[];
  queryParams?: { name: string; required: boolean; type: string; description?: string }[];
  requestBody?: Record<string, unknown> | null;
  responseSuccess?: { status: number; bodyExample?: Record<string, unknown> };
};

export const CALL_CENTER_ENDPOINT_SPECS: PublicEndpointSpec[] = [
  {
    id: "public.request-data",
    method: "GET",
    path: "/public/request-data",
    authRequired: false,
    description: "Returns this specification (no authentication).",
    responseSuccess: { status: 200, bodyExample: { meta: {}, endpoints: [] } },
  },
  {
    id: "public.health",
    method: "GET",
    path: "/public/health",
    authRequired: false,
    description: "Liveness check for call center API routes (no authentication).",
    responseSuccess: { status: 200, bodyExample: { ok: true, service: "call-center" } },
  },
  {
    id: "auth.me",
    method: "GET",
    path: "/auth",
    authRequired: true,
    description: "Current call center agent profile and assigned workshops.",
    headers: [{ name: "Authorization", required: true, example: "Bearer <firebase_id_token>" }],
  },
  {
    id: "auth.register",
    method: "POST",
    path: "/auth",
    authRequired: true,
    description: "Create call center agent (BMS super_admin or workshop_owner Bearer only).",
    headers: [
      { name: "Authorization", required: true, when: "BMS admin Firebase token", example: "Bearer <admin_id_token>" },
    ],
    requestBody: {
      email: "agent@example.com",
      password: "min6chars",
      name: "Agent Name",
      role: "agent",
      assignedWorkshops: ["<ownerUid>"],
    },
    responseSuccess: { status: 201 },
  },
  {
    id: "auth.patch",
    method: "PATCH",
    path: "/auth",
    authRequired: true,
    description: "Update agent workshops / suspend / role (BMS admin).",
    headers: [{ name: "Authorization", required: true, example: "Bearer <admin_id_token>" }],
    requestBody: {
      agentUid: "<firebaseUid>",
      assignedWorkshops: ["<ownerUid>"],
      suspended: false,
    },
  },
  {
    id: "did-lookup.get",
    method: "GET",
    path: "/did-lookup",
    authRequired: true,
    description: "Resolve inbound DID to workshop (did_mappings or branch phone).",
    queryParams: [{ name: "did", required: true, type: "string", description: "E.164 or local phone" }],
  },
  {
    id: "did-lookup.post",
    method: "POST",
    path: "/did-lookup",
    authRequired: true,
    description: "Create/update DID mapping (call_center_admin only).",
    requestBody: {
      did: "+61400000000",
      ownerUid: "<ownerUid>",
      branchId: "<branchId|null>",
      branchName: "Optional",
      label: "Optional",
    },
  },
  {
    id: "workshops.list",
    method: "GET",
    path: "/workshops",
    authRequired: true,
    description: "Workshops the agent may access.",
  },
  {
    id: "workshops.detail",
    method: "GET",
    path: "/workshops/{ownerUid}",
    authRequired: true,
    description:
      "Branches (each with weekly hours + bookingLimitPerDay), services, staff for one workshop.",
  },
  {
    id: "branches.list",
    method: "GET",
    path: "/branches",
    authRequired: true,
    description:
      "All branches for a workshop owner (same payload shape as GET /branches/{branchId} per row). Agents: any ownerUid. BMS staff: must have access to that workshop.",
    queryParams: [
      { name: "ownerUid", required: false, type: "string", description: "Workshop owner Firebase UID; or use X-Tenant-Id" },
      {
        name: "date",
        required: false,
        type: "YYYY-MM-DD",
        description: "Optional; sets daySchedule on each branch for that weekday",
      },
    ],
    headers: [{ name: "X-Tenant-Id", required: false, example: "<ownerUid>" }],
    responseSuccess: {
      status: 200,
      bodyExample: {
        ownerUid: "<ownerUid>",
        total: 2,
        branches: [],
      },
    },
  },
  {
    id: "branches.detail",
    method: "GET",
    path: "/branches/{branchId}",
    authRequired: true,
    description:
      "Branch details: weekly hours, bookingLimitPerDay, daySchedules. Call center agents may read any branch. BMS staff scoped by workshop; ownerUid / X-Tenant-Id must match branch if sent.",
    queryParams: [
      { name: "ownerUid", required: false, type: "string", description: "BMS staff: must match branch if provided; ignored for call center agents" },
      {
        name: "date",
        required: false,
        type: "YYYY-MM-DD",
        description: "Optional; if set, daySchedule copies that weekday from daySchedules",
      },
    ],
    headers: [{ name: "X-Tenant-Id", required: false, example: "<ownerUid>" }],
    responseSuccess: {
      status: 200,
      bodyExample: {
        branch: {
          id: "<branchId>",
          name: "",
          address: "",
          phone: "",
          email: "",
          timezone: "Australia/Sydney",
          status: "Active",
          hours: { Monday: { open: "09:00", close: "17:00" } },
          daySchedules: {
            Sunday: { dayOfWeek: "Sunday", closed: true, open: null, close: null },
            Monday: { dayOfWeek: "Monday", closed: false, open: "09:00", close: "17:00" },
          },
          daySchedule: null,
          bookingLimitPerDay: 20,
        },
      },
    },
  },
  {
    id: "customers.search",
    method: "GET",
    path: "/customers",
    authRequired: true,
    description: "Search customers by phone/email/name within tenant.",
    queryParams: [
      { name: "ownerUid", required: false, type: "string", description: "Or use X-Tenant-Id header" },
      { name: "q", required: true, type: "string" },
      { name: "searchBy", required: false, type: "phone|email|name" },
    ],
    headers: [{ name: "X-Tenant-Id", required: false, when: "if ownerUid not in query", example: "<ownerUid>" }],
  },
  {
    id: "customers.create",
    method: "POST",
    path: "/customers",
    authRequired: true,
    description: "Create a customer record in BMS for the given workshop.",
    requestBody: {
      ownerUid: "<ownerUid>",
      name: "Customer Name",
      email: "optional",
      phone: "optional",
      vehicleNumber: "optional",
      vehicleDetails: { make: "", model: "", year: "", colour: "", vin: "", engineNumber: "", bodyType: "" },
      notes: "optional",
    },
    responseSuccess: { status: 201, bodyExample: { success: true, customerId: "<id>", name: "" } },
  },
  {
    id: "customers.detail",
    method: "GET",
    path: "/customers/{customerId}",
    authRequired: true,
    description: "Screen pop: profile, vehicles, booking history.",
    queryParams: [{ name: "ownerUid", required: false, type: "string" }],
    headers: [{ name: "X-Tenant-Id", required: false, example: "<ownerUid>" }],
  },
  {
    id: "customers.vehicles.list",
    method: "GET",
    path: "/customers/{customerId}/vehicles",
    authRequired: true,
    description: "List vehicles registered under a customer.",
    queryParams: [
      { name: "ownerUid", required: false, type: "string", description: "Optional; inferred from customer doc if omitted" },
    ],
  },
  {
    id: "customers.vehicles.create",
    method: "POST",
    path: "/customers/{customerId}/vehicles",
    authRequired: true,
    description:
      "Add a vehicle. Requires rego OR registrationNumber OR vehicleNumber. Optional: make, model, year, colour, bodyType, engineNumber, vin, vinChassis, mileage, notes, or vehicleDetails: { ... }.",
    requestBody: {
      ownerUid: "<optional>",
      rego: "ABC123",
      registrationNumber: "ABC123",
      make: "Toyota",
      model: "Camry",
      year: "2020",
      colour: "White",
      bodyType: "Sedan",
      engineNumber: "",
      vin: "",
      vinChassis: "",
      mileage: "45000",
      notes: "",
      vehicleDetails: { make: "", model: "" },
    },
    responseSuccess: {
      status: 201,
      bodyExample: {
        success: true,
        vehicleId: "<id>",
        vehicle: {
          id: "<id>",
          rego: "ABC123",
          registrationNumber: "ABC123",
          make: "Toyota",
          model: "Camry",
          year: "2020",
          colour: "White",
          vin: "",
          vinChassis: "",
          engineNumber: "",
          bodyType: "Sedan",
          mileage: "45000",
          notes: "",
          createdAt: null,
          updatedAt: null,
        },
      },
    },
  },
  {
    id: "services.list",
    method: "GET",
    path: "/services",
    authRequired: true,
    description: "List services for a workshop, optionally filtered by branch. Includes available staff per service.",
    queryParams: [
      { name: "ownerUid", required: false, type: "string", description: "Or use X-Tenant-Id header" },
      { name: "branchId", required: false, type: "string", description: "Filter services assigned to this branch" },
      { name: "summary", required: false, type: "1", description: "If 1, omit checklist[] (keep checklistCount only)" },
    ],
    headers: [{ name: "X-Tenant-Id", required: false, when: "if ownerUid not in query", example: "<ownerUid>" }],
    responseSuccess: {
      status: 200,
      bodyExample: {
        services: [
          {
            id: "<serviceId>",
            name: "Full Service",
            description: "Complete vehicle service",
            price: 299,
            duration: 120,
            icon: "",
            imageUrl: "",
            branches: ["<branchId>"],
            staff: [{ id: "<staffUid>", name: "John", role: "staff", branchId: "<branchId>" }],
            checklistCount: 5,
            checklist: [
              { index: 0, name: "Oil change", description: "", done: false, imageUrl: "" },
            ],
          },
        ],
        total: 1,
      },
    },
  },
  {
    id: "services.detail",
    method: "GET",
    path: "/services/{serviceId}",
    authRequired: true,
    description: "Full service detail: checklist items, assigned branches (with names), and available staff.",
    responseSuccess: {
      status: 200,
      bodyExample: {
        service: {
          id: "<serviceId>",
          name: "Full Service",
          description: "Complete vehicle service",
          price: 299,
          duration: 120,
          icon: "",
          imageUrl: "",
          branches: [{ id: "<branchId>", name: "Main Branch" }],
          staff: [{ id: "<staffUid>", name: "John", role: "staff", branchId: "<branchId>" }],
          checklist: [{ name: "Oil change", description: "Replace engine oil" }],
        },
      },
    },
  },
  {
    id: "services.checklists",
    method: "GET",
    path: "/services/checklists",
    authRequired: true,
    description:
      "All service checklist / todo template items for a workshop (for call-center scripts and customer explanations). Flat `todos` plus grouped `services`.",
    queryParams: [
      { name: "ownerUid", required: false, type: "string" },
      { name: "branchId", required: false, type: "string", description: "Only services linked to this branch" },
    ],
    headers: [{ name: "X-Tenant-Id", required: false, example: "<ownerUid>" }],
    responseSuccess: {
      status: 200,
      bodyExample: {
        ownerUid: "<ownerUid>",
        branchId: null,
        totalServices: 2,
        totalChecklistItems: 8,
        services: [
          {
            serviceId: "<id>",
            serviceName: "Full Service",
            checklist: [
              { index: 0, name: "Oil change", description: "", done: false, imageUrl: "" },
            ],
          },
        ],
        todos: [
          {
            serviceId: "<id>",
            serviceName: "Full Service",
            index: 0,
            name: "Oil change",
            description: "",
            done: false,
            imageUrl: "",
          },
        ],
      },
    },
  },
  {
    id: "bookings.list",
    method: "GET",
    path: "/bookings",
    authRequired: true,
    description:
      "List bookings for a workshop with optional filters (status, date, branch, customer). With no limit param, returns all matching Firestore rows (server loads in batches). Optional limit=N caps rows (max 50000). Each booking includes an additionalIssues array with full extra-work details (titles, pricing, customer response, completion, image URLs).",
    queryParams: [
      { name: "ownerUid", required: false, type: "string" },
      { name: "status", required: false, type: "string" },
      { name: "date", required: false, type: "YYYY-MM-DD" },
      { name: "branchId", required: false, type: "string" },
      { name: "customerId", required: false, type: "string" },
      { name: "limit", required: false, type: "number|string" },
      { name: "all", required: false, type: "boolean" },
    ],
    headers: [{ name: "X-Tenant-Id", required: false, example: "<ownerUid>" }],
  },
  {
    id: "bookings.create",
    method: "POST",
    path: "/bookings",
    authRequired: true,
    description: "Creates booking in BMS Firestore (workshop sees it in admin + app).",
    requestBody: {
      ownerUid: "<ownerUid>",
      branchId: "<branchId>",
      branchName: "optional",
      date: "YYYY-MM-DD",
      time: "HH:mm",
      pickupTime: "HH:mm|null",
      services: [{ serviceId: "<id>", serviceName: "", price: 0, duration: 0, staffId: "optional" }],
      client: "Name",
      clientEmail: "",
      clientPhone: "",
      customerId: "optional",
      vehicleNumber: "",
      vehicleDetails: {
        make: "",
        model: "",
        year: "",
        registrationNumber: "",
        mileage: "",
        bodyType: "",
        colour: "",
        vinChassis: "",
        vin: "",
        engineNumber: "",
        notes: "",
      },
      notes: "",
    },
    responseSuccess: {
      status: 201,
      bodyExample: { success: true, bookingId: "", bookingCode: "", status: "", totalPrice: 0, totalDuration: 0 },
    },
  },
  {
    id: "bookings.availability",
    method: "GET",
    path: "/bookings/availability",
    authRequired: true,
    description:
      "Available/blocked slots for a branch/date/services. Includes merged branch booking context: weekly hours, bookingLimitPerDay, daySchedule (open/close), plus dailyLimit/currentBookings.",
    queryParams: [
      { name: "ownerUid", required: false, type: "string" },
      { name: "branchId", required: true, type: "string" },
      { name: "date", required: true, type: "YYYY-MM-DD" },
      { name: "serviceIds", required: true, type: "string", description: "Comma-separated service ids" },
    ],
    headers: [{ name: "X-Tenant-Id", required: false, example: "<ownerUid>" }],
    responseSuccess: {
      status: 200,
      bodyExample: {
        available: true,
        dayOfWeek: "Monday",
        branch: {
          id: "<branchId>",
          name: "",
          hours: {},
          daySchedules: {},
          daySchedule: { dayOfWeek: "Monday", closed: false, open: "09:00", close: "17:00" },
          bookingLimitPerDay: 20,
        },
        branchHours: { open: "09:00", close: "17:00" },
        allSlots: ["09:00", "09:30"],
        blockedSlots: [],
        availableSlots: ["09:00", "09:30"],
        dailyLimitReached: false,
        dailyLimit: 20,
        currentBookings: 3,
      },
    },
  },
  {
    id: "bookings.detail",
    method: "GET",
    path: "/bookings/{id}",
    authRequired: true,
    description: "Job card: services, tasks, additional issues, progress.",
  },
  {
    id: "bookings.additional-issues.list",
    method: "GET",
    path: "/bookings/{id}/additional-issues",
    authRequired: true,
    description: "List extra work (additional issues) on a booking and summary counts.",
  },
  {
    id: "bookings.additional-issues.patch",
    method: "PATCH",
    path: "/bookings/{id}/additional-issues/{issueId}",
    authRequired: true,
    description: "Record customer accept/reject after phone approval (issue must be approved with price).",
    requestBody: { customerResponse: "accept" },
  },
  {
    id: "call-logs.create",
    method: "POST",
    path: "/call-logs",
    authRequired: true,
    description: "Record a call in BMS for workshop visibility; optional callCenterCallId links to external CRM.",
    requestBody: {
      ownerUid: "<ownerUid>",
      branchId: "optional",
      callerPhone: "",
      callerName: "optional",
      customerId: "optional",
      bookingId: "optional",
      direction: "inbound|outbound",
      purpose: "booking|progress_check|extra_work_approval|general_inquiry|complaint|other",
      duration: 0,
      notes: "",
      outcome: "",
      callCenterCallId: "optional Supabase id for cross-reference",
    },
  },
  {
    id: "call-logs.list",
    method: "GET",
    path: "/call-logs",
    authRequired: true,
    description: "Retrieve call log history for a workshop, optionally filtered by customer or booking.",
    queryParams: [
      { name: "ownerUid", required: true, type: "string" },
      { name: "customerId", required: false, type: "string" },
      { name: "bookingId", required: false, type: "string" },
      { name: "limit", required: false, type: "number" },
    ],
  },
  {
    id: "webhooks.list",
    method: "GET",
    path: "/webhooks",
    authRequired: true,
    description: "call_center_admin only.",
  },
  {
    id: "webhooks.create",
    method: "POST",
    path: "/webhooks",
    authRequired: true,
    description: "call_center_admin only.",
    requestBody: {
      url: "https://your-app.com/webhooks/bms",
      events: [
        "booking.status_changed",
        "booking.additional_issue",
        "booking.issue_priced",
        "booking.completed",
        "booking.canceled",
      ],
      secret: "optional signing secret",
      description: "",
    },
  },
  {
    id: "webhooks.delete",
    method: "DELETE",
    path: "/webhooks?id={webhookId}",
    authRequired: true,
    description: "call_center_admin only.",
  },
];
